//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace GymBooster.WindowsSilverPhone.GymBoosterService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Training", Namespace="http://schemas.datacontract.org/2004/07/GymBooster.Core.Entities")]
    public partial class Training : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime EndTimeField;
        
        private System.Collections.ObjectModel.ObservableCollection<GymBooster.WindowsSilverPhone.GymBoosterService.Exercise> ExercisesField;
        
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GymBooster.WindowsSilverPhone.GymBoosterService.Exercise> Exercises {
            get {
                return this.ExercisesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExercisesField, value) != true)) {
                    this.ExercisesField = value;
                    this.RaisePropertyChanged("Exercises");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Exercise", Namespace="http://schemas.datacontract.org/2004/07/GymBooster.Core.Entities")]
    public partial class Exercise : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<GymBooster.WindowsSilverPhone.GymBoosterService.ExcerciseSerie> SeriesField;
        
        private GymBooster.WindowsSilverPhone.GymBoosterService.ExcerciseType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<GymBooster.WindowsSilverPhone.GymBoosterService.ExcerciseSerie> Series {
            get {
                return this.SeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriesField, value) != true)) {
                    this.SeriesField = value;
                    this.RaisePropertyChanged("Series");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GymBooster.WindowsSilverPhone.GymBoosterService.ExcerciseType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExcerciseType", Namespace="http://schemas.datacontract.org/2004/07/GymBooster.Core.Entities")]
    public partial class ExcerciseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExcerciseSerie", Namespace="http://schemas.datacontract.org/2004/07/GymBooster.Core.Entities")]
    public partial class ExcerciseSerie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime EndTimeField;
        
        private int NumberOfRepsField;
        
        private System.DateTime StartTimeField;
        
        private double WeightInKilosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfReps {
            get {
                return this.NumberOfRepsField;
            }
            set {
                if ((this.NumberOfRepsField.Equals(value) != true)) {
                    this.NumberOfRepsField = value;
                    this.RaisePropertyChanged("NumberOfReps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WeightInKilos {
            get {
                return this.WeightInKilosField;
            }
            set {
                if ((this.WeightInKilosField.Equals(value) != true)) {
                    this.WeightInKilosField = value;
                    this.RaisePropertyChanged("WeightInKilos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GymBoosterService.IAmGymBoosterService")]
    public interface IAmGymBoosterService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAmGymBoosterService/GetAllTrainings", ReplyAction="http://tempuri.org/IAmGymBoosterService/GetAllTrainingsResponse")]
        System.IAsyncResult BeginGetAllTrainings(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<GymBooster.WindowsSilverPhone.GymBoosterService.Training> EndGetAllTrainings(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAmGymBoosterServiceChannel : GymBooster.WindowsSilverPhone.GymBoosterService.IAmGymBoosterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllTrainingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllTrainingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<GymBooster.WindowsSilverPhone.GymBoosterService.Training> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<GymBooster.WindowsSilverPhone.GymBoosterService.Training>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AmGymBoosterServiceClient : System.ServiceModel.ClientBase<GymBooster.WindowsSilverPhone.GymBoosterService.IAmGymBoosterService>, GymBooster.WindowsSilverPhone.GymBoosterService.IAmGymBoosterService {
        
        private BeginOperationDelegate onBeginGetAllTrainingsDelegate;
        
        private EndOperationDelegate onEndGetAllTrainingsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllTrainingsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public AmGymBoosterServiceClient() {
        }
        
        public AmGymBoosterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AmGymBoosterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmGymBoosterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmGymBoosterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAllTrainingsCompletedEventArgs> GetAllTrainingsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GymBooster.WindowsSilverPhone.GymBoosterService.IAmGymBoosterService.BeginGetAllTrainings(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllTrainings(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<GymBooster.WindowsSilverPhone.GymBoosterService.Training> GymBooster.WindowsSilverPhone.GymBoosterService.IAmGymBoosterService.EndGetAllTrainings(System.IAsyncResult result) {
            return base.Channel.EndGetAllTrainings(result);
        }
        
        private System.IAsyncResult OnBeginGetAllTrainings(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((GymBooster.WindowsSilverPhone.GymBoosterService.IAmGymBoosterService)(this)).BeginGetAllTrainings(callback, asyncState);
        }
        
        private object[] OnEndGetAllTrainings(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<GymBooster.WindowsSilverPhone.GymBoosterService.Training> retVal = ((GymBooster.WindowsSilverPhone.GymBoosterService.IAmGymBoosterService)(this)).EndGetAllTrainings(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllTrainingsCompleted(object state) {
            if ((this.GetAllTrainingsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllTrainingsCompleted(this, new GetAllTrainingsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllTrainingsAsync() {
            this.GetAllTrainingsAsync(null);
        }
        
        public void GetAllTrainingsAsync(object userState) {
            if ((this.onBeginGetAllTrainingsDelegate == null)) {
                this.onBeginGetAllTrainingsDelegate = new BeginOperationDelegate(this.OnBeginGetAllTrainings);
            }
            if ((this.onEndGetAllTrainingsDelegate == null)) {
                this.onEndGetAllTrainingsDelegate = new EndOperationDelegate(this.OnEndGetAllTrainings);
            }
            if ((this.onGetAllTrainingsCompletedDelegate == null)) {
                this.onGetAllTrainingsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllTrainingsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllTrainingsDelegate, null, this.onEndGetAllTrainingsDelegate, this.onGetAllTrainingsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override GymBooster.WindowsSilverPhone.GymBoosterService.IAmGymBoosterService CreateChannel() {
            return new AmGymBoosterServiceClientChannel(this);
        }
        
        private class AmGymBoosterServiceClientChannel : ChannelBase<GymBooster.WindowsSilverPhone.GymBoosterService.IAmGymBoosterService>, GymBooster.WindowsSilverPhone.GymBoosterService.IAmGymBoosterService {
            
            public AmGymBoosterServiceClientChannel(System.ServiceModel.ClientBase<GymBooster.WindowsSilverPhone.GymBoosterService.IAmGymBoosterService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAllTrainings(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllTrainings", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<GymBooster.WindowsSilverPhone.GymBoosterService.Training> EndGetAllTrainings(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<GymBooster.WindowsSilverPhone.GymBoosterService.Training> _result = ((System.Collections.ObjectModel.ObservableCollection<GymBooster.WindowsSilverPhone.GymBoosterService.Training>)(base.EndInvoke("GetAllTrainings", _args, result)));
                return _result;
            }
        }
    }
}
